defmodule BuzzKillfeed.Seeds.NextSeeds do
  alias BuzzKillfeed.Repo
  alias BuzzKillfeed.Next


  def seed do
    nexts = [
              "...Just Click It Already",
              "...Please, We Really Need The Clickthroughs",
              "Blew the Whole City Away",
              "Broke The Internet",
              "Cannot Be Unseen",
              "Could Be The Best Thing That Has Ever Happened",
              "Doesn't Matter To Anyone",
              "Doesn't Live Up To Anyone's Expectations",
              "Fellow Criminals Would Be Proud Of",
              "Gets More Epic By The Nanosecond",
              "Has A Tragic Twist",
              "Is A Bit of All Right",
              "Is A Complete Disappointment",
              "Is A Giant Nothingburger, But That Never Stopped Us",
              "Is A Recipe For Disaster",
              "Is A Train Wreck",
              "Is All Our Fault",
              "Is Binge-Worthy",
              "Is Completely Overhyped, But We're Out Of Ideas",
              "Is Proof It's A Slow News Day",
              "Is Of No Consquence At All",
              "Is Hysterical",
              "Is Leaving Billions of People Homeless and Starving",
              "Is Probably Not Worth Your Time",
              "Is Really Dumb, But You'll Click Anyway",
              "Is So Cringey You'll Want To Look Away, BUT YOU CAN'T",
              "Is Straight From Your Worst Nightmare. Trust Me",
              "Is Testing My Faith",
              "Is Truly Disturbing",
              "Is Utterly Boring, But We Know You Have Nothing Better To Do Right Now",
              "Is Yet Another Internet Rabbit Hole",
              "Is The Best Thing We've Seen All Year",
              "Is The Best Thing You'll See In The ENTIRE World",
              "Is The Best Thing In The History of Ever",
              "Made Me -- And Millions of Women -- Feel Great",
              "Made Me LQTM",
              "Made a Lot of Scientists Very, Very Upset",
              "Might Be The Cutest Thing In the Universe. Seriously!",
              "Should Be On Everyone's Bucket List",
              "Shows How Little We Care About What's Important",
              "Shows Why We Can't Have Nice Things",
              "Will Allow You To Die Happy",
              "Will Be Your New Favorite Acid Trip",
              "Will Blow Your Mind",
              "Will Creep You Right Out",
              "Will Give You All The Feels",
              "Will Give You the Heebie-Jeebies",
              "Will Have You In Tears",
              "Will Literally Scare You to Death. No Really, You'll Actually Die",
              "Will Make All Your Other Life Events Pale In Comparison And You'll Just Want to End It All Immediately",
              "Will Make You Be Like...WHOA",
              "Will Make You Crap Your Pants",
              "Will Make You Cry Blood",
              "Will Make You Cry Out For Brain Bleach",
              "Will Make You Wish You'd Get Out More Often",
              "Will Make You Wish You Could Get That Two Minutes of Your Life Back",
              "Will Make Your Life Worth Living",
              "Will Render You Completely Unable To Get Any Work Done",
              "Will Utterly SHOCK You!!! . . . Will It Though?",
              "Will Stun You",
              "Will Tingle Your Naughty Bits",
              "Will Warm the Cockles of Your Heart. Whatever That Means",
              "Won The Internet",
              "You'll Never Forget",
              "You'll Definitely Want To See Before Your Friends Do",
              "You'll Retweet Until You're Banned",
            ]
            |> Enum.map(fn v -> [value: v] end)
    Repo.insert_all(Next, nexts, on_conflict: :nothing)

  end
end
