defmodule BuzzKillfeed.Seeds.PredicateSeeds do
  alias BuzzKillfeed.Predicate
  alias BuzzKillfeed.Repo

  def seed() do
    predicates = [
                   "...Just Click It Already",
                   "Absolutely Deserve A Dirty Look In Response",
                   "All Tea Lovers Need In Their Lives",
                   "Are A Hot Mess",
                   "Are A Trap!",
                   "Are Actual Christmas Miracles",
                   "Are An Absolute Must To Get Your First Promotion",
                   "Are Bigger On The Inside",
                   "Are Crazy... LIKE A FOX",
                   "Are DTF",
                   "Are Evidence of Aliens from Outer Space",
                   "Are For Households With Children",
                   "Are Goin' Down, Sir! Goin' Down!",
                   "Are Going The Right Way For A Smack",
                   "Are Headed TO THE MOON!!!",
                   "Are Innocent-Looking Enough, But Actually Quite Dangerous",
                   "Are Invading Your Home",
                   "Are Invading Your Home",
                   "Are Kinda Cool, But You Could Probably Skip It",
                   "Are Mildly Amusing If You're Into That Kind Of Thing",
                   "Are No Small Moon",
                   "Are Not Worth A Freakout",
                   "Are Old And Busted",
                   "Are Operating Out of a D.C. Pizza Restaurant",
                   "Are On The DL",
                   "Are Required To Get Your First Promotion",
                   "Aren't Funny Any More",
                   "Aren't As Funny As They Think They Are",
                   "Are Sponge-Worthy",
                   "Are The Reason We Can't Have Nice Things",
                   "Are Too Good To Be True",
                   "Are Trying Way Too Hard",
                   "Are a Worse Threat Than Terrorism",
                   "Are a Worse Threat Than Terrorism",
                   "Aren't Cute",
                   "Aren't The Worst Thing You Could Read About",
                   "Aren't the Droids You're Looking For",
                   "Believe They Can Do Absolutely Everything",
                   "Boldly Show How Different Life Is In the Two Koreas",
                   "Broke All The Stereotypes",
                   "Broke The Internet",
                   "Californians Are Tired Of",
                   "Can't Be Explained by Singing",
                   "Can't Stop Smiling",
                   "Cause STDs",
                   "Circuses Don't Want You To Know",
                   "Could Double As A Demonic Lamp",
                   "Creep You Right Out",
                   "Designed a Balkan City",
                   "Doctors Don't Want You To Know",
                   "Doctors Will Hate You For",
                   "Don't Actually Exist",
                   "Don't Care",
                   "Dressed In Drag",
                   "Embarrassed Us More Than Our Own Parents",
                   "Everyone's Giving The Side Eye",
                   "Fled in Terror",
                   "Grew Up To Be Ugly",
                   "Hate Us Cuz They Ain't Us",
                   "Haunt Your Nightmares",
                   "Have A Dark Side",
                   "Have A Lot Of Rules For Women",
                   "Have A Tragic Twist",
                   "Have Been Stuck On Kylie Jenner's Wrist For Years",
                   "Have Ever Been Photographed",
                   "Have Unconfirmed Evidence of Election Hacking",
                   "Herald Peace on Earth and Goodwill Toward Men",
                   "Hijacked Military Social Media Accounts",
                   "Hilariously Hit On A Hot Reporter",
                   "If You Don't Click It I'll Get Fired Please I Need My Job",
                   "Indicate You're Awesome",
                   "Are Kinda Cool, But You Could Probably Skip It",
                   "Just Had A Baby",
                   "Just Landed A $150M Investment",
                   "Just Might Give You Cancer",
                   "Lie Like a Rug",
                   "Made Me LQTM",
                   "Turned My Stomach",
                   "Made the Kessel Run in 12 Parsecs",
                   "Mean Something Changed In the Matrix",
                   "Mean You Have A Terminal Illness",
                   "Mean You're Adopted",
                   "Mean You're Going To Space",
                   "Mean Your Relationship is Doomed",
                   "Men Are Turning Gay Over",
                   "Men Should All Be Ashamed Of",
                   "Might Be Illegal",
                   "Might Be Keeping A Dirty Secret",
                   "Most Sheeple Don't Know",
                   "Nail It With a Poem",
                   "Need A Place In Your Home",
                   "Need To Get Off My Lawn",
                   "No One Told You How Weird They Were",
                   "Nobody Knows About",
                   "Only Beautiful People Will Understand",
                   "Only Clumsy People Will Understand",
                   "Only Men Will Understand",
                   "Only Women Will Understand",
                   "People Make Every Day",
                   "People Make Every Day",
                   "Pets Have Ever Swallowed",
                   "Post Way Too Many Selfies",
                   "Prove Everyone Will Be Eating Bugs By Next Year",
                   "Prove Jealous Girlfriends Are Actually The Best",
                   "Prove San Francisco Blows Goats",
                   "Prove Teachers Can Have Fun Too",
                   "Prove There's A War On Christmas",
                   "Prove You're A Complete Jerk",
                   "Prove You're With The Right Person",
                   "Prove You're a Sociopath",
                   "Ran Yelping Like Scalded Dogs",
                   "Really Know Where Their Towels Are",
                   "Remind Everyone of Used Car Salesmen",
                   "Rock You To Your Core",
                   "Rocked the Chess World",
                   "Scream Your Awesomeness",
                   "Signal He's Cheating",
                   "Single People Know Too Well",
                   "Taste Just Like Iguana",
                   "Taste Just Like Iguana",
                   "The Decepticons Adore",
                   "The Government is Hiding from You",
                   "The Russians Definitely Did Not Hack Into. They Didn't Do It, Nobody Saw Them, You Can't Prove Anything!!!",
                   "They Don't Want You to See",
                   "Think They're Getting Away With It",
                   "Today's Kids Will Never Understand",
                   "Truly Capture The Intensity of Dungeons and Dragons",
                   "Used To Bullseye Womp Rats In Their T-16 Back Home",
                   "Warm Your Heart",
                   "We Hate",
                   "We Love",
                   "Were Forced to Leave a Sex Club",
                   "Were In The Military",
                   "Were Revealed In X-Rays",
                   "Will Amaze You",
                   "Will Blow Your Mind",
                   "Will Bring More Sandwiches Into Your Life",
                   "Will Convince You To Make A Week of Vegan Dinners",
                   "Will Derail Your Career",
                   "Will Dogwalk You If You Don't Leave Them Alone",
                   "Will JUST DO IT LIVE!!",
                   "Will Literally Blow Your Mind. Like, Up",
                   "Will Make You Care About Climate Change",
                   "Will Make You Cry Out For Brain Bleach",
                   "Will Make You Cry",
                   "Will Make You Punch Yourself In The Face",
                   "Will Make You Vomit",
                   "Will Make Your Commute Less Crappy",
                   "Will Never Grow Up",
                   "Will Ruin Your Life Forever",
                   "Will Wake You Up, Sheeple!",
                   "Will Shoot Your Eye Out",
                   "Wish They Were A Real Live Boy",
                   "Won The Internet",
                   "You Can't Even",
                   "You Can't Literally Even",
                   "You Can't Remotely Trust",
                   "You Have Probably Already Done and Don't Know It",
                   "You Have To Tell Your Mother About",
                   "You Ignore At Your Peril",
                   "You Must Do To Get Your First Promotion",
                   "You Should Avoid At All Costs",
                   "You Should Never Do In London",
                   "You Should Never Eat",
                   "You Should Not Click On No Matter What",
                   "You Should See Before You Die",
                   "You Won't Believe",
                 ]
                 |> Enum.map(fn v -> [value: v] end)
    Repo.insert_all(Predicate, predicates, on_conflict: :nothing)

  end
end
