name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    env:
      MIX_ENV: cli
      DB_DATABASE: buzz_killfeed_test
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: localhost
      DB_PORT: 3306

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.12.2' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get & mix deps.compile
    - name: Set up database
      run:  |
        sudo systemctl start mysql.service
        mix mix ecto.create && mix ecto.migrate
    - name: Run tests
      run: mix test
