name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          # will assign a random free host port
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      MIX_ENV: test
      DB_USER:  postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_HOST: localhost
      DB_DATABASE: app_test

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.12.2' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
    - name: Set up git private repo
      # https://github.com git:github.com
      run: |
        git config --global url."https://${{ secrets.CHECKOUT_CREDS }}@github.com/shannonwells".insteadOf "https://github.com"
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build
          priv/plts
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Set up database
      run:  |
        mix ecto.create
        mix ecto.migrate
    - name: Run tests
      run: mix test
